import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.scss'
import Header from '../components/Navbar/Header'
import Hero from '../components/Hero/Hero'
import Destination from '../components/Destinations/Destination'
import Blog from '../components/Blog/Blog'
import Footer from '../components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Destination />
      <Blog />
      <Footer />
    </>
  )
}
